### ISSUE TITLE
UDPNAR terminated by signal SIGBUS (Misaligned address error)

### ISSUE THREAD

**Issue by ntoxeg** [opennars/OpenNARS-for-Applications#159] opened 2022-04-15 08:34 UTC
UDPNAR crashes when I try to send some beliefs to it, so far it always happens after sending second line. It was compiled without `openmp` support with LLVM Clang. The exact crash line says
```
'./NAR UDPNAR 127.0.0.1 50000...' terminated by signal SIGBUS (Misaligned address error)
```
I send data via a Python `socket` object from `socket`.

**Comment by patham9** [comment] 2022-04-15 11:32
Are you sending a zero-byte at the end?
To test if it is indeed this issue, please try this:
NAR_AddInput.sh with zero-byte: **(fine)**
`printf "$1\0" | nc -w 1 -u 127.0.0.1 50000 &`
NAR_AddInput.sh without zero-byte: **(not fine)**
`printf "$1" | nc -w 1 -u 127.0.0.1 50000 &`
then:
```
sh NAR_AddInput.sh "<a --> b>."
sh NAR_AddInput.sh "<b --> c>."
```

**Comment by ntoxeg** [comment] 2022-04-15 12:19
Yes, I use a wrapper function of
```
def send_input(socket: socket.socket, input_: str) -> None:
    """Send input to NARS server"""
    socket.sendto((input_ + "\0").encode(), ("127.0.0.1", 50000))
```

**Comment by patham9** [comment] 2022-04-15 14:27
Hi! Interesting, I wasn't able to replicate the issue yet, but I have a replacement solution for you. I can also fix it if the following replacement solution is no option, so please also tell me what OS you are using.
First some context:
I was always very careful regarding adding OS-dependent stuff to ONA as I wanted it to remain as portable as C99 itself. I don't see a reason for a reasoning system to be strongly OS-dependent, or even to be dependent on POSIX API's other than for fine control over multi-threading, or to run a single reasoner as a distributed system across multiple computers, but ideally even both of these should be optional.

Hence, my replacement solution is to add a file NAR.sh with the following content:
```
nc -l -k -p 50000 | ./NAR shell &
while true; do printf "1\n" | nc -w -u 1 127.0.0.1 50000; sleep 1; done
```
This more flexible script does in 2 lines what UDP.c / UDP.c does in 150.

The example script NAR_AddInput.sh would then look like this:
`printf "$1\n" | nc -w 1 127.0.0.1 50000`
which is almost the same as before, just that the last sent character needs to be \n instead of \0, which is also the only change you will need to make in your Python code.

Can you please see if NAR.sh works for you as functionally equivalent replacement to UDPNAR? Also your overall opinion about replacing UDPNAR with the much simpler "netcat+ONA shell" solution would be helpful!

**Comment by patham9** [comment] 2022-04-15 14:31
Hi! Interesting, I wasn't able to replicate the issue yet, but I have a replacement solution for you. I can also fix it if the following replacement solution is no option, so please also tell me what OS you are using.
First some context:
I was always very careful regarding adding OS-dependent stuff to ONA as I wanted it to remain as portable as C99 itself. I don't see a reason for a reasoning system to be strongly OS-dependent, or even to be dependent on POSIX API's other than for fine control over multi-threading, or to run a single reasoner as a distributed system across multiple computers, but ideally even both of these should be optional.

Hence, my replacement solution is to add a file NAR.sh with the following content:
```
nc -l -k -p 50000 | ./NAR shell &
sleep 1
while true; do printf "1\n" | nc -w 1 127.0.0.1 50000; sleep 1; done
```
This more flexible script does in 2 lines what UDP.c / UDP.c does in 150.

The example script NAR_AddInput.sh would then look like this:
`printf "$1\n" | nc -w 1 127.0.0.1 50000`
which is almost the same as before, just that the last sent character needs to be \n instead of \0, which is also the only change you will need to make in your Python code.

Can you please see if NAR.sh works for you as functionally equivalent replacement to UDPNAR? Also your overall opinion about replacing UDPNAR with the much simpler "netcat+ONA shell" solution would be helpful!

**Comment by ntoxeg** [comment] 2022-04-15 14:48
I’ll try your solution, though I have a problem with NAR shell too — I tried to work around the problem by just using the shell and send to it via `stdin` (via the usual `subprocess` `process.stdin` mechanics) but it hangs on reading from it.
I build on macOS with LLVM Clang (to have OpenMP support).

**Comment by ntoxeg** [comment] 2022-04-15 14:51
I’m getting `nc: missing port with option -l` from your script, by the way.

**Comment by ntoxeg** [comment] 2022-04-15 14:56
Another annoying thing: I am executing from another directory so I basically have to hardcode the path to `NAR` in this script, otherwise it gets a bit more complicated.

**Comment by ntoxeg** [comment] 2022-04-15 15:04
Ok, this is weird, I get similar hangups with this when reading from `stdout` with just `NAR shell` — it seems this happens when there is no new output. **However**, after sending some statements trying to read just yields `''` instead of blocking, I have no idea why...

**Comment by patham9** [comment] 2022-04-15 16:29
These seem different issues, but here my take on it:

1. netcat: there are multiple implementations, the BSD version has different parameters than the GNU version. And Mac OS has an ancient version of the BSD version (forked 2005) by default, so is not compatible with the newer BSD versions even. You can install an up-to-date version via homebrew. But maybe that's a good indicator that it's better to keep UDPNAR  in ONA, since at least POSIX is portable while networking-related tools between UNIX OS tend to differ. I can make it optional in the compilation.

2. **"Another annoying thing: I am executing from another directory so I basically have to hardcode the path to NAR in this script"**
That's about how binaries are invoked, I didn't design this. :) You can also put the NAR binary under /usr/local/bin, or you can include the ONA directory in your $PATH environment variable, both will allow you do use ONA without having the path specified.

3. **"I’ll try your solution, though I have a problem with NAR shell too — I tried to work around the problem by just using the shell and send to it via stdin (via the usual subprocess process.stdin mechanics) but it hangs on reading from it."**
Pythons subprocess handling is quite generic and complex, you most likely missed something there. ONA shell has been tested on dozens of platforms in the meanwhile so it's very suspicious that you face issues there. Please take a look at NAR.py, it communicates with NAR via stdin/stdout. You can test it by executing /misc/Python/count_sheep.py

To also resolve the original issue: do you mind sharing your Python code with me? Then I can probably replicate the issue.

**Comment by patham9** [comment] 2022-04-15 16:44
Also: above you mentioned you are not using OpenMP, below on the other hand you mentioned you enabled it.
So the same issue appears in both cases and hence is unrelated to multithreading, correct?

**Comment by ntoxeg** [comment] 2022-04-15 18:12
Ok, so I’ll try the `NAR.py` approach too, it uses some `pexpect` module I’m not familiar with but maybe it will “just work”.
As for my code it’s basically adapted from what I’ve found in the repo anyway (mostly the toothbrush_udp example).

To read from the subprocess I just use this:
```python
def get_output(process: subprocess.Popen) -> str:
    """Get output from NARS server"""
    return process.stdout.readline().strip()
```
The process is started like
```python
process = subprocess.Popen(
    process_cmd,
    stdout=subprocess.PIPE,
    stdin=subprocess.PIPE,
    universal_newlines=True,
)
```
(for UDPNAR of course I don’t use `stdin`)

Yes, `python3 evaluation.py` passes (python==3.9.12), I will include the output just in case: https://pastebin.com/V9WUKMHM

I am not using OpenMP for testing purposes indeed.

As for the point (2.): what I mean is that with invoking binaries I can just have some env variable like `NARS_HOME` that I can use as a setting to locate them. But with a bash script invoking things I have to also extend it so that it navigates to its own directory (because the working dir is set to the dir of the Python script). That is of course a minor issue but certainly makes the solution less elegant.

**Comment by ntoxeg** [comment] 2022-04-15 18:16
Anyway, the actual problem with reading from NAR shell with `subprocess` is that if there is no output, then my script will hang until there is, and if I interrupt this somehow (like with a keyboard interrupt), then afterwards I just get `'’`.

**Comment by patham9** [comment] 2022-04-15 18:42
I remember several oddities with the subprocess module in Python3, like suddenly needing Shell=True etc. in some cases even though Python2 didn't need it, but whether this has anything to do with your case is just speculation without having your code.
I suggest not to re-invent the wheel but to use the existing Python interface: NAR.py
We used it successfully in multiple projects, even on Windows and there are multiple examples in the /examples/Python directory which help getting started with it, including the count_sheeps.py which worked correctly on your end according your output.

Regarding the UDP interface: I couldn't replicate the issue yet, but I'm still investigating.

**Comment by patham9** [comment] 2022-04-15 19:19
@ntoxeg : Can you please start UDPNAR with `./NAR UDPNAR 127.0.0.1 50000 100000 true`

and then run:

```
import socket
ip = "127.0.0.1"
port = 50000
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.sendto(('a. :|:\0').encode(), (ip, port))
sock.sendto(('b. :|:\0').encode(), (ip, port))
sock.sendto(('c. :|:\0').encode(), (ip, port))
```

and show the the output of NAR?
If this works then it doesn't seem to be UDPNAR's fault.

**Comment by ntoxeg** [comment] 2022-04-15 20:41
Ok, so I didn’t expect this but it turns out it’s actually **specific input that crashes it**.
You can try it yourself by doing `<a --> [x]>. :|:` and `<a --> [y]>. :|:`.

So I guess I misunderstand something about NAL then? You can’t say at some point that “a has property x” and then that “a has property y”? Technically I also made a mistake (I think, I’m not sure) of assigning multiple properties to the same entity.

Of course, if this is a NAL mistake then it would be nice to have an actual error message about what went wrong instead of just a cryptic crash.

**Comment by ntoxeg** [comment] 2022-04-15 20:43
Oh, the shell **doesn't** crash from that though...

**Comment by patham9** [comment] 2022-04-15 21:11
No worries there are no such restrictions. Previous inputs are perfectly valid and shouldn't crash it. I would have been very surprised if ONA-shell would have crashed on such input as it's extremely stable since it got labelled "ONA". It seems the issue is in the glue code which tries to put input to ONA. Will investigate when back home. In the meanwhile precise steps to replicate the crash would be helpful. Did you pass the input through the UDP code I posted in my last comment?

**Comment by ntoxeg** [comment] 2022-04-15 21:25
Yes, it’s the same setup but instead of your input just do
```bash
sock.sendto(('<a --> [x]>. :|:\0').encode(), (ip, port))
sock.sendto(('<a --> [y]>. :|:\0').encode(), (ip, port))
```

**Comment by patham9** [comment] 2022-04-16 20:26
Good news: I was able to replicate the issue on Mac OS, it might be some POSIX incompatibility. I'm currently traveling but will make sure there will be a fix on Monday or earlier.

**Comment by patham9** [comment] 2022-04-16 23:16
Fixed with https://github.com/opennars/OpenNARS-for-Applications/commit/c00a650fdb469cb634550db4cfe5b4a1a5bc9e37
This fix also reveals an artifact of code which was written for smaller atom sizes than the later v0.8.x introduced. With up to 65K atoms however this code is inefficient.
I will make it use the bounded hashmap asap, knowing that there can at most be COMPOUND_TERM_SIZE_MAX=64 in default config (atom -> int) associations representing how often the atom appears in the term, a much more reasonable size than maintaining 65 K of them.

**Closed by patham9** 2022-04-16 23:16 UTC

**Comment by patham9** [comment] 2022-04-18 16:52
Also for variable_id array: https://github.com/opennars/OpenNARS-for-Applications/commit/4842a562fdb01d2e6d426fe02d170118b806a065 hashmap version for speedup addressing https://github.com/opennars/OpenNARS-for-Applications/issues/161 is underway as well

**Comment by patham9** [comment] 2022-04-18 16:52
Also for variable_id array: https://github.com/opennars/OpenNARS-for-Applications/commit/4842a562fdb01d2e6d426fe02d170118b806a065 hashmap version for speedup addressing https://github.com/opennars/OpenNARS-for-Applications/issues/161 is underway as well
